version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install python3
            sudo apt-get install python3-pip
            python3 --version
            pip3 --version
            sudo pip3 install -q awscli --upgrade
            aws --version
            which aws
      - run:
          name: Build Artifact
          command: |
            cd webapp
            sudo apt-get update
            sudo apt-get install maven
            mvn package
            cd target
            ls -al
            cd
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh codedeploy_artifact/
            cp webapp/target/ROOT.war codedeploy_artifact/
            cp appspec.yml codedeploy_artifact/
            cd codedeploy_artifact/
            zip  csye6225-web-app-${CIRCLE_BUILD_NUM}.zip *
            ls -al
            pwd
            chmod 777 csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
            ls -al
            pwd
            aws s3 cp csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${aws_bucket_name}
      - run:
          name: Upload Artifact to S3
          command: |
            echo ${AWS_ACCESS_KEY_ID}
            echo ${AWS_SECRET_ACCESS_KEY}
            echo ${aws_bucket_name}
            ls -al
            cd /home/circleci/project/codedeploy_artifact
            ls -ltr
            aws s3 cp csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${aws_bucket_name}
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy final " 
            aws deploy create-deployment --region us-east-1 --application-name csye6225-webapp --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${aws_bucket_name},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip