version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install python3
            sudo apt-get install python3-pip
            python3 --version
            pip3 --version
            sudo pip3 install -q awscli --upgrade
            aws --version
            which aws
      - run:
          name: Build Artifact
          command: |
            cd webapp
            sudo apt-get update
            sudo apt-get install maven
            mvn package
            cd target
            ls -al
            cd
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/target/ROOT.war *.sh *.yml
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            cd
            cd codedeploy_artifact
            ls -ltr
            aws s3 sync . s3://${aws_bucket_name} --region us-east-1
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy" 
            aws deploy create-deployment --application-name csye6225-webapp --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${aws_bucket_name},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip